/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/AYu5ov1GWmZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"


export default function PagOpinion() {
  return (
    
    <>
    <div className="mx-auto max-w-2xl space-y-8 py-12 px-4 sm:px-6 lg:px-8">
      <div>
        <h2 className="text-2xl font-bold">Deja tu opinión</h2>
        <p className="text-muted-foreground">Comparte tu experiencia con nosotros.</p>
      </div>
      <form className="space-y-4">
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div>
            <Label htmlFor="name">Nombre</Label>
            <Input id="name" placeholder="Ingresa tu nombre" />
          </div>
          <div>
            <Label htmlFor="email">Correo electrónico</Label>
            <Input id="email" type="email" placeholder="Ingresa tu correo electrónico" />
          </div>
        </div>
        <div>
          <Label htmlFor="review">Opinión</Label>
          <Textarea id="review" placeholder="Escribe tu opinión aquí..." className="min-h-[150px]" />
        </div>
        <Button type="submit" className="w-full">
          Enviar opinión
        </Button>
      </form>
      <div>
        <h2 className="text-2xl font-bold">Opiniones de otros usuarios</h2>
        <div className="space-y-6">
          <div className="flex items-start gap-4">
            <Avatar className="w-10 h-10 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <div className="font-medium">John Doe</div>
                <div className="text-xs text-muted-foreground">2 días atrás</div>
              </div>
              <div>¡Excelente servicio! El producto cumplió con todas mis expectativas.</div>
            </div>
          </div>
          
          <div className="flex items-start gap-4">
            <Avatar className="w-10 h-10 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>EM</AvatarFallback>
            </Avatar>
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <div className="font-medium">Emily Martinez</div>
                <div className="text-xs text-muted-foreground">3 días atrás</div>
              </div>
              <div>
                Tuve algunos problemas con la entrega, pero el equipo de soporte fue muy amable y resolvió el problema
                rápidamente.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </>

  )
}
