/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/uQWjf14aIoW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function DbForm() {
  return (
    <div className="w-full max-w-md mx-auto p-6 bg-card rounded-lg shadow-md">
      <div className="space-y-4">
        <h1 className="text-2xl font-bold">Configurar nivel de sonido para semáforo</h1>
        <p className="text-muted-foreground">
          Establece el nivel de decibelios (dB) que activará el color rojo del semáforo en tu aula de clase.
        </p>
        <form className="space-y-4">
          <div className="grid gap-2">
            <label htmlFor="decibel-level" className="text-base font-medium">
              Nivel de decibelios (dB)
            </label>
            <Input id="decibel-level" type="number" placeholder="Ingresa el nivel de dB" className="max-w-[200px]" />
          </div>
          <Button type="submit" className="w-full">
            Guardar
          </Button>
        </form>
        <div className="bg-muted rounded-md p-4">
          <div className="flex items-center justify-between">
            <span className="text-base font-medium">Nivel de sonido actual:</span>
            <span className="text-2xl font-bold">75 dB</span>
          </div>
          <p className="text-muted-foreground text-sm">
            El semáforo se encenderá en rojo cuando el nivel de sonido supere los 75 dB.
          </p>
        </div>
      </div>
    </div>
  )
}
