/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YEOHnN1GIHv
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"



export function Graphics() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container space-y-8 px-4 md:px-6">
        <div className="text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Classroom Sound Monitoring</h2>
          <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Keep track of noise levels in your classrooms with our real-time sound monitoring system.
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <Card>
            <CardHeader>
              <CardTitle>Sound Level</CardTitle>
            </CardHeader>
            <CardContent>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Noise Levels</CardTitle>
            </CardHeader>
            <CardContent>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Noise Hotspots</CardTitle>
            </CardHeader>
            <CardContent>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  )
}

